name: Vivliostyle build in Docker

on:
  push:
    branches: [ dockerbuild ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: vivliostyle/action@v1
        with:
          input: jppb/publication.json
          cli-version: 5
          artifact-name: book-ubuntu
          if-no-files-found: error